import os
import shutil
import subprocess
import logging

logger = logging.getLogger("modem_compile")

from smarts.utils import utils

config_files = {}

def get_makefiles():
    makefiles = []
    for f in os.listdir('./'):
        if 'smarts' in f:
            makefiles.append(f)

    return makefiles

def extract_modset(executable: str) -> str:
    executable = executable.lower()
    split = executable.split('.')

    for itm in split:
        if 'modset' in itm:
            return itm.split(':')[1]

    return False

description = """

Compiles all ModEM configuration files that were generated by make_config_files.

It looks for makefiles in the format of:

  > Makefile.modset:modsetname.Debug.MPI.SP

and loads the modset followed by modsetname.

This test can take quite a lot of time! So be prepared.

** Options **

If you pass in `-f`, `--force` to Smarts, this test will assume that
make_config_files was already run and the src_dir contains the
above Makefiles. The -f argument is intended to avoid re-running
make_config_files again and again.

"""

    
class modem_compile:
    test_name = "Compile ModEM Test"
    test_description = "Compile all ModEM configurations (Except HDF5)"
    dependencies = ['make_config_files']
    ncpus = 1

    def run(self, env, result, src_dir, test_dir, hpc=None, *args, **kwargs):

        print('kwargs:', kwargs)
        force = kwargs.get('force', False)

        gnu_modsets = env.list_modsets(name="GNU")
        if not gnu_modsets:
            result.result = "FAILED"
            result.msg = "This env file had no modests with the name 'GNU'"
            return result.result

        if not os.path.isdir(os.path.join(src_dir, 'f90')):
            result.result = "FAILED"
            result.msg = f"{src_dir} does not appear to a ModEM source directory"
            return result.result

        # Change directory to copy of ModEM in the test directory
        ''' If force is passed in as a test option, then the user doesn't want
        to re-run make_config_files, so the src_dir should hold the Makefiles 
        files for us to use, so use that instead.
        
        '''
        if force: # If force is pass
            logger.info("Force is true - going into the src directory")
            os.chdir(os.path.join(src_dir, 'f90'))
        else:
            logger.info("Force is false - going into the `make_config_files`")
            os.chdir(os.path.join('..', 'make_config_files', './ModEM-Model', 'f90'))


        makefiles = utils.all_matches(os.listdir('.'), 
                                      matches=['Makefile', 'modset'],
                                      discards=['.f90', 'log', 'bak'])

        logger.info(f"Makefiles: {makefiles}")

        if len(makefiles) == 0:
            result.result = "FAILED"
            result.msg = "Found no makefile!"
            return result.result


        for makefile in makefiles:
            if 'HDF5' in makefile:
                logger.skipped(f"Skipping HDF5 - {makefile}")
                continue

            modset = extract_modset(makefile)

            logger.info("")
            logger.info(f"Testing makefile: '{makefile}'...")

            if 'gfortran' in modset:
                modset_name = 'GNU'
            elif 'ifort' in modset:
                modset_name = 'INTEL'

            modsets = env.list_modsets(name=modset_name)

            if len(modsets) == 0:
                logger.skipped(f"Modset '{modset_name}' is not on this enviorment. Skipping this makefile")
                continue

            for modset in modsets:
                logger.info("")
                logger.info(f"Loading modset: {modset}")
                if not env.load_modset(modset):
                    result.result = "FAILED"
                    result.msg = "Could not load gnu modset {modset}"
                    return result.result

                log_filename=f'../../log.make.{modset}.{makefile}.out'
                log_file=open(log_filename, 'w')
                logger.info(f"Compiling: '{makefile}' with  {modset} - logging into: '{os.path.abspath(log_filename)}'")

                try:
                    ierr = subprocess.run(['make', '-f', makefile, 'clean'], stdout=log_file, stderr=log_file, check=True)
                except subprocess.CalledProcessError as e:
                    result.result = "FAILED"
                    result.msg = f"Error when calling 'make clean' on {makefile} - error in: {os.path.abspath(log_filename)}"
                    return result.result

                try:
                    ierr = subprocess.run(['make', '-f', makefile], stdout=log_file, stderr=log_file, check=True)
                except subprocess.CalledProcessError as e:
                    result.result = "FAILED"
                    result.msg = f"Error when calling 'make' on {makefile} - error in: {os.path.abspath(log_filename)}"
                    return result.result

                if '3D' in makefile:
                    modem_exe_default = 'Mod3DMT'
                    executable_name = f'Mod3DMT.Modset:{modset}.{makefile}'.replace('.makefile.', '.')
                    logger.info(f"Excpeted 3D built exe: {modem_exe_default}")
                elif '2D' in makefile:
                    modem_exe_default = 'Mod2DMT'
                    executable_name = f'Mod2DMT.Modset:{modset}.{makefile}'.replace('.makefile.', '.')
                    logger.info(f"Excpeted 2D built exe: {modem_exe_default}")
                elif 'spherical' in makefile:
                    modem_exe_default = 'Mod3DMT_sph'

                    executable_name = f'Mod3DMT_sph.Modset:{modset}.{makefile}'.replace('.makefile.', '.')
                    logger.info(f"Excpeted spherical built exe: {modem_exe_default}")
                else:
                    modem_exe_default = 'Mod3DMT'
                    executable_name = f'Mod3DMT.Modset:{modset}.{makefile}'.replace('.makefile.', '.')
                    logger.info(f"Excpeted default built exe: {modem_exe_default}")

                if not os.path.isfile(modem_exe_default):
                    result.result = "FAILED"
                    result.msg = f"Could not find the default executable: {modem_exe_default} for {makefile}"
                    return result.result

                try:
                    ierr = subprocess.run(['make', '-f', makefile, 'clean'], stdout=log_file, stderr=log_file, check=True)
                except subprocess.CalledProcessError as e:
                    result.result = "FAILED"
                    result.msg = f"Error when calling 'make clean' on {makefile} - error in: {os.path.abspath(log_filename)}"
                    return result.result

                shutil.move(modem_exe_default, executable_name)
                logger.passed(f"Succesfully compiled {makefile} with {modset} - exe: {executable_name}\n")


        result.result = "PASSED"
        result.msg = "Successfully compiled all ModEM Versions"
